/*
 * Copyright (c) 2026 Evolveum and contributors
 *
 * This work is licensed under European Union Public License v1.2. See LICENSE file for details.
 *
 */
package com.evolveum.polygon.conndev.devtools.yaml.codegen.pydantic;

import com.evolveum.polygon.conndev.devtools.yaml.codegen.ShapeNaming;
import com.evolveum.polygon.conndev.devtools.yaml.config.ShapeFileConfig;
import com.evolveum.polygon.conndev.devtools.yaml.shape.AnyShape;
import com.evolveum.polygon.conndev.devtools.yaml.shape.DelegatedObjectShape;
import com.evolveum.polygon.conndev.devtools.yaml.shape.DocumentShape;
import com.evolveum.polygon.conndev.devtools.yaml.shape.LeafShape;
import com.evolveum.polygon.conndev.devtools.yaml.shape.LeafShape.LeafType;
import com.evolveum.polygon.conndev.devtools.yaml.shape.ListShape;
import com.evolveum.polygon.conndev.devtools.yaml.shape.MapShape;
import com.evolveum.polygon.conndev.devtools.yaml.shape.ObjectShape;
import com.evolveum.polygon.conndev.devtools.yaml.shape.PathShape;
import com.evolveum.polygon.conndev.devtools.yaml.shape.ScriptShape;
import com.evolveum.polygon.conndev.devtools.yaml.shape.ShapeIdentity;
import com.evolveum.polygon.conndev.devtools.yaml.shape.UnionShape;
import com.evolveum.polygon.conndev.devtools.yaml.shape.YamlProperty;
import com.evolveum.polygon.conndev.devtools.yaml.shape.YamlShape;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Renders the document as a drop-in Pydantic module for midpilot-connector-gen: the
 * {@code _Configuration} strictness base (strict, extra-forbid, explicit-null rejection with the
 * {@code nullable_fields} exceptions), the {@code _script()} metadata helper that the script
 * syntax validation reads via {@code json_schema_extra}, the keyword-key aliases
 * ({@code json}/{@code class}/{@code schema}/{@code from}) and one closed model per distinct
 * object structure — named after the same {@link ShapeNaming} as the JSONSchema.
 */
public final class PydanticGenerator {

    /** The attribute-path model (the runtime's {@code {type, value}} format declaration). */
    private static final String PATH_CLASS = "_AttributePath";

    /** The YAML keys whose Python field name must differ from the key itself (midpilot's established aliases). */
    private static final Map<String, String> KEYWORD_ALIASES = Map.of(
            "json", "json_mapping",
            "class", "class_name",
            "schema", "schema_name",
            "from", "from_value");

    private static final Set<String> PYTHON_KEYWORDS = Set.of(
            "False", "None", "True", "and", "assert", "async", "await", "break", "class", "continue",
            "def", "del", "elif", "else", "except", "finally", "for", "from", "global", "if", "import",
            "in", "is", "lambda", "nonlocal", "not", "or", "pass", "raise", "return", "try", "while",
            "with", "yield");

    private final DocumentShape document;
    private final ShapeFileConfig config;
    private final List<ShapeNaming.Named> named;
    private final Map<String, String> identityToName = new LinkedHashMap<>();

    public PydanticGenerator(DocumentShape document, ShapeFileConfig config) {
        this.document = document;
        this.config = config;
        this.named = ShapeNaming.assign(document, config);
        for (ShapeNaming.Named entry : named) {
            identityToName.put(ShapeIdentity.of(entry.shape()), entry.name());
        }
    }

    public String generate() {
        StringBuilder sb = new StringBuilder();
        sb.append("# Generated by ").append(document.generatedBy()).append(" for the ")
                .append(document.name()).append(" connector.\n");
        sb.append("# Scanned from the @Yaml.*-annotated entry builders at build time.\n");
        sb.append("# Do not edit by hand - regenerate with: mvn conndev-yaml:generate\n\n");
        sb.append("\"\"\"The ").append(document.name()).append(" connector YAML document.\n\n");
        sb.append("Generated from the @Yaml.*-annotated entry builders; absent keys preserve the\n");
        sb.append("framework defaults and an explicit null is only valid where the shape file\n");
        sb.append("allows it (the nullable_fields of the individual models).\n\"\"\"\n\n");
        // Classes are emitted in document order, so a parent may reference a class defined later
        // (or itself, through a cycle) - PEP 563 keeps every annotation lazy until the module is
        // fully loaded, which is when Pydantic resolves them.
        sb.append("from __future__ import annotations\n\n");
        sb.append("from typing import Any, ClassVar\n\n");
        sb.append("from pydantic import BaseModel, ConfigDict, Field, ValidationInfo, field_validator\n\n\n");

        configurationBase(sb);
        sb.append("\n\n");
        scriptHelper(sb);
        sb.append("\n\n");
        attributePath(sb);

        for (ShapeNaming.Named entry : named) {
            sb.append("\n\n");
            objectClass(sb, entry.shape(), "_" + entry.name());
        }

        sb.append("\n\n");
        documentClass(sb);
        return sb.toString();
    }

    private void configurationBase(StringBuilder sb) {
        sb.append("class _Configuration(BaseModel):\n");
        sb.append("    model_config = ConfigDict(strict=True, extra=\"forbid\")\n");
        sb.append("    nullable_fields: ClassVar[frozenset[str]] = frozenset()\n\n");
        sb.append("    @field_validator(\"*\", mode=\"before\")\n");
        sb.append("    @classmethod\n");
        sb.append("    def reject_explicit_null(cls, value: Any, info: ValidationInfo) -> Any:\n");
        sb.append("        if value is None and info.field_name not in cls.nullable_fields:\n");
        sb.append("            raise ValueError(\"expected a configured value, not null\")\n");
        sb.append("        return value\n");
    }

    private void scriptHelper(StringBuilder sb) {
        sb.append("def _script(*, expression: bool = False, empty_body: bool = False) -> Any:\n");
        sb.append("    return Field(default=None, json_schema_extra={\"script\": True, \"expression\": expression, \"empty_body\": empty_body})\n");
    }

    private void attributePath(StringBuilder sb) {
        sb.append("class ").append(PATH_CLASS).append("(_Configuration):\n");
        sb.append("    type: str\n");
        sb.append("    value: str\n\n");
        sb.append("    @field_validator(\"type\")\n");
        sb.append("    @classmethod\n");
        sb.append("    def validate_path_type(cls, value: str) -> str:\n");
        sb.append("        if value.upper() not in {\"JSON_PATH\", \"JSON_POINTER\", \"SCIM\"}:\n");
        sb.append("            raise ValueError(\"expected JSON_PATH, JSON_POINTER or SCIM\")\n");
        sb.append("        return value\n");
    }

    private void documentClass(StringBuilder sb) {
        sb.append("class ").append(config.pythonDocumentClass()).append("(_Configuration):\n");
        sb.append("    \"\"\"The ").append(document.name()).append(" connector YAML document (the union of its slots).\"\"\"\n\n");
        for (YamlProperty property : document.topLevel().values()) {
            field(sb, "    ", property);
        }
    }

    private void objectClass(StringBuilder sb, ObjectShape shape, String className) {
        sb.append("class ").append(className).append("(_Configuration):\n");
        if (shape.description() != null) {
            sb.append("    \"\"\"").append(escape(shape.description())).append("\"\"\"\n");
        }
        List<String> nullable = new ArrayList<>();
        boolean first = true;
        for (YamlProperty property : shape.properties().values()) {
            if (first) {
                sb.append("\n");
                first = false;
            }
            field(sb, "    ", property);
            if (property.nullable()) {
                nullable.add(pyFieldName(property.key()));
            }
        }
        if (!nullable.isEmpty()) {
            sb.append("\n    nullable_fields: ClassVar[frozenset[str]] = frozenset({");
            sb.append(String.join(", ", nullable.stream().map(v -> "\"" + v + "\"").toList()));
            sb.append("})\n");
        }
    }

    private void field(StringBuilder sb, String indent, YamlProperty property) {
        String name = pyFieldName(property.key());
        String key = property.key();
        boolean aliased = !name.equals(key);
        String annotation = annotation(property.shape());
        boolean optional = !property.required();

        sb.append(indent).append(name).append(": ").append(annotation);
        if (optional) {
            sb.append(" | None");
        }
        if (property.shape() instanceof ScriptShape script) {
            sb.append(" = ").append(scriptCall(script));
        } else if (optional) {
            sb.append(" = Field(default=None").append(aliased ? ", alias=\"" + key + "\"" : "").append(")");
        } else if (aliased) {
            sb.append(" = Field(alias=\"").append(key).append("\")");
        }
        sb.append("\n");
    }

    /** The Groovy-script Field metadata (the midpilot syntax checker reads it from json_schema_extra). */
    private String scriptCall(ScriptShape script) {
        List<String> args = new ArrayList<>();
        if (script.expression()) {
            args.add("expression=True");
        }
        if (script.emptyBody()) {
            args.add("empty_body=True");
        }
        return "_script(" + String.join(", ", args) + ")";
    }

    /** The Python annotation of a shape (the class references use the generated class names). */
    private String annotation(YamlShape shape) {
        return switch (shape) {
            case LeafShape l -> switch (l.type()) {
                case LeafType.STRING -> "str";
                case LeafType.BOOLEAN -> "bool";
                case LeafType.INTEGER -> "int";
                case LeafType.NUMBER -> "float";
            };
            case ScriptShape s -> "str";
            case PathShape p -> "str | " + PATH_CLASS;
            case ObjectShape o -> "_" + identityToName.get(ShapeIdentity.of(o));
            case ListShape l -> "list[" + annotation(l.item()) + "]";
            case MapShape m -> "dict[str, " + annotation(m.value()) + (m.nullableValue() ? " | None" : "") + "]";
            case UnionShape u -> String.join(" | ", u.alternatives().stream().map(this::annotation).toList());
            case AnyShape a -> "Any";
            case DelegatedObjectShape d -> throw new IllegalStateException(
                    "Unresolved DelegatedObjectShape reached the generator: " + d.source());
        };
    }

    /** The Python field name of a YAML key: the established alias, a keyword-safe name, or the key itself. */
    private String pyFieldName(String key) {
        if (KEYWORD_ALIASES.containsKey(key)) {
            return KEYWORD_ALIASES.get(key);
        }
        if (PYTHON_KEYWORDS.contains(key)) {
            return key + "_value";
        }
        return key;
    }

    private static String escape(String text) {
        return text.replace("\\", "\\\\").replace("\"\"\"", "\\\"\"\"").replace("\n", " ");
    }
}
