/*
 * Copyright (c) 2025 Evolveum and contributors
 *
 * This work is licensed under European Union Public License v1.2. See LICENSE file for details.
 *
 */
package com.evolveum.polygon.conndev.annotations;

/**
 *
 * The GroovyApi annotation is used to mark interfaces or classes that are intended to be interacted with from a Groovy environment.
 *
 * This annotation does not provide any special functionality and are part of Groovy Scripting Contract.
 *
 * Usage of this annotation is optional but recommended for clarity.
 */
public @interface Groovy {


    @interface Convenience {

    }

    @interface Declaration {

    }

    @interface Contract {

    }

    /**
     * Alternate spelling of method / function which delegates to origin. Useful for words with multiple spellings
     * to support alternate code generated by AI.
     */
    @interface AlternateSpelling {

    }
}
